#### BAB III (LISTS AND DICTIONARIES)

##### List

In [1]:
# Creating an empty list in Python 

height = []
type(height)

list

In [2]:
# A list containing heights 

height_list = [1.76, 1.64, 1.79, 1, 57]
height_list

[1.76, 1.64, 1.79, 1, 57]

In [3]:
# A list containing str and float 

name_height_list = ["Tom", 1.76, "Harry", 1.64, "Lisa", 1.79, "Mona", 1,57]
name_height_list

['Tom', 1.76, 'Harry', 1.64, 'Lisa', 1.79, 'Mona', 1, 57]

##### Operasi Manupulasi Daftar yang Berbeda

In [4]:
# Begin with number zero

lang = ['python', 'c', 'java']

print(lang[0] + ' is very easy to learn for Data Science')
print(lang[1] + ' is the first language I have learnt')
print(lang[2] + ' is difficult to learn for Data Science') 

python is very easy to learn for Data Science
c is the first language I have learnt
java is difficult to learn for Data Science


In [5]:
# Changing java with cobol language

lang = ['python', 'c', 'java']
print("old list: ", lang)
lang[2] = 'Cobol'
print("new list: ", lang)

old list:  ['python', 'c', 'java']
new list:  ['python', 'c', 'Cobol']


In [6]:
# Using For loop

language_list = ['python', 'c', 'cobol']
for language in language_list:
    print("language is: ", language)

language is:  python
language is:  c
language is:  cobol


In [7]:
# Using list's len() method

language_list = ['python', 'c', 'cobol']
print("element in the list: ", len(language_list))

element in the list:  3


In [8]:
# Using list's append() method


language_list = ['Python', 'C', 'Cobol']
language_list.append('Java')
print('Update list is:', language_list)

Update list is: ['Python', 'C', 'Cobol', 'Java']


In [9]:
# Adding a new language .net

language_list = ['python', 'c', 'cobol', 'java']
language_list.insert(2, '.net')
print("modified list is: ", language_list)

modified list is:  ['python', 'c', '.net', 'cobol', 'java']


In [10]:
# Removing some element from the list

language_list = ['python', 'c', '.net', 'cobol', 'java']

# Remove element by name
language_list.remove('cobol')
print("update list: ", language_list)

# Remove element by index
language_list.pop(3)
print("latest list: ", language_list)

update list:  ['python', 'c', '.net', 'java']
latest list:  ['python', 'c', '.net']


In [11]:
# Applying different methods to remove an element

number_list = [1, 2, 3, 4, 1]
number_list.remove(4)
print("List after remove() example: ", number_list)

number_list = [1, 2, 3, 4, 1]
number_list.pop(4)
print("List after pop() example: ", number_list)

number_list = [1, 2, 3, 4, 1]
del(number_list[4])
print("List after del() example: ", number_list)

List after remove() example:  [1, 2, 3, 1]
List after pop() example:  [1, 2, 3, 4]
List after del() example:  [1, 2, 3, 4]


In [12]:
# Sorting list in ascending or descending order

language_list = ['Python', 'C', '.net', 'Cobol', 'Java']
language_list.sort()
print("Sort in ascending order: ", language_list)

language_list = ['Python', 'C', '.net', 'Cobol', 'Java', 'C#']
language_list.sort(reverse=True)
print("Sort in descending order: ", language_list)

Sort in ascending order:  ['.net', 'C', 'Cobol', 'Java', 'Python']
Sort in descending order:  ['Python', 'Java', 'Cobol', 'C#', 'C', '.net']


##### Perbedaan List dan Tuple

In [13]:
# Tuple

tuple_example = ('CS', 'IT', 'EC', 'ME')
print("Tuple example: ", tuple_example)
print("Data type of the example is", type(tuple_example))

Tuple example:  ('CS', 'IT', 'EC', 'ME')
Data type of the example is <class 'tuple'>


##### Kamus (Dictionary)

In [14]:
# Creating a dictionary

dict_example = {
    'brand' : 'Hyundai',
    'model' : 'Creta',
    'Type' : 'SUV',
    'year' : '2017'
}

print("Dictionary example ", dict_example)

Dictionary example  {'brand': 'Hyundai', 'model': 'Creta', 'Type': 'SUV', 'year': '2017'}


In [15]:
# Using key and get() method

# Access the brand value by key
car_brand_by_key = dict_example['brand']
print("car brand by key: ", car_brand_by_key)

# Access the brand value by get()
print("car brand by method: ", dict_example.get('brand'))

car brand by key:  Hyundai
car brand by method:  Hyundai


In [16]:
# Changing value in the dictionary

dict_example['year'] = 2018
print("updated dict: ", dict_example)

updated dict:  {'brand': 'Hyundai', 'model': 'Creta', 'Type': 'SUV', 'year': 2018}


In [17]:
# For loop

# Printing all keys
for car_property in dict_example:
    print("key in dict: ", car_property)

key in dict:  brand
key in dict:  model
key in dict:  Type
key in dict:  year


In [18]:
for car_property_value in dict_example.values():
    print('value in dict: ', car_property_value)

value in dict:  Hyundai
value in dict:  Creta
value in dict:  SUV
value in dict:  2018


In [19]:
# Displaying car details in a key-value pair

for car_property, car_property_value in dict_example.items():
    print(car_property, car_property_value)

brand Hyundai
model Creta
Type SUV
year 2018


#### BAB IV (PAKET, FUNGSI, dan PERULANGAN)

##### Fungsi Help

In [20]:
# Using hel() function

help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



##### Import Paket

In [21]:
# Math package provided by python

import math

# Define area as variable area
area = 0

# Define radius as variable r
r = 5.89

# Calculate area
area = math.pi * r**2
print("area of the land is: ", area)

area of the land is:  108.98844649760245


##### Memanggil Fungsi

In [22]:
def myFunction() :
    print("Hello Word")

# Calling functoin
myFunction()

Hello Word


##### Melewati Parameter Dalam Suatu Fungsi

In [23]:
# Defining a function to return sum of two numbers

def addTwoNumbers(a, b) :
    return a + b

addTwoNumbers(9, 8)

17

##### Parameter Yang Tidak Diketahui Dalam Suatu Fungsi 

In [ ]:
# Sum() function to add three numbers

def addFunction(*args) :
    return sum(args)

addFunction(9, 4, 8)

21

In [25]:
# Commenting the first print line after function declaration

def myFunction() :
    # print(my_text)
    my_text = 'I am also learning'
    print(my_text)

# Define a global scope variable
my_text = "I am also learning python for Data Science"
myFunction()
print(my_text)

I am also learning
I am also learning python for Data Science


##### Fungsi Lamda

In [26]:
# Normal function and lambda function

def multiply(x) :
    return x * 5

multiply(2)

10

##### While dan Loop

In [27]:
# While loop code snippet

x = 1
while x < 4:
    print(x)
    x += 1

1
2
3


In [28]:
# For loop code snippet

for letter in "Science":
    print(letter)

S
c
i
e
n
c
e


#### BAB V (FUNDAMENTAL NUMPY)

##### Import Paket Numpy

In [29]:
# Importing a NumPy package
import numpy as np # type: ignore

##### Menggunakan Array Numpy Daripada List

In [30]:
# Using NumPy Array

import numpy as np # type: ignore

distance = [55, 60, 45]
speed = [6, 10, 7]
dist = np.array(distance)
spd = np.array(speed)
time = dist/spd
time

array([9.16666667, 6.        , 6.42857143])

##### Membuat Array Numpy

In [31]:
# NumPy attributes

# Data type
print("Data type of array: ", time.dtype)

# No. of dimensions
print("No. of dimensions: ", time.ndim)

# Size of each dimensions
print("Size of each dimensions: ", time.shape)

# Total size of array
print("Total size of array: ", time.size)

Data type of array:  float64
No. of dimensions:  1
Size of each dimensions:  (3,)
Total size of array:  3


##### Membuat Array Numpy

In [32]:
# Creating arrays with random values

np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

print("x1 ndim: ", x1.ndim)
print("x1 shape: ", x1.shape)
print("x1 size: ", x1.size)

print("x2 ndim: ", x2.ndim)
print("x2 shape: ", x2.shape)
print("x2 size: ", x2.size)

print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)


x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
x2 ndim:  2
x2 shape:  (3, 4)
x2 size:  12
x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [33]:
# Using arange() function

f = np.arange(0, 20, 5)
print("Sequential array with steps of 5:\n", f)

Sequential array with steps of 5:
 [ 0  5 10 15]


##### Mengakses Elemen Dalam Array Numpy

In [34]:
# Accessing elements of the arrays

print("1-d array: ", x1)
print("Second element of first array: ", x1[1])
print("Last element of first array: ", x1[-1])
print("first element of first array: ", x1[0])

1-d array:  [5 0 3 3 7 9]
Second element of first array:  0
Last element of first array:  9
first element of first array:  5


In [35]:
# Accessing first elements of 2D and 3D arrays

print("2-d array:\n", x2)
print("First elements of 2-d array:\n", x2[0,0])
print("3-d array:\n", x3)
print("First elements of 3-d array:\n", x3[0,0,0])

2-d array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
First elements of 2-d array:
 3
3-d array:
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
First elements of 3-d array:
 8


##### Pemotongan (Slincing) Dalam Array Numpy

In [36]:
# Creating 1D array

# Create an array
x = np.arange(10)
print("Our array: ", x)
print("First five elements: ", x[:5])
print("Elements after index 5: ", x[5:])
print("Middle sub-array: ", x[4:7])
print("Every other element: ", x[::2])
print("Every other element, starting at index 1: ", x[1::2])
print("Elements in reversed order: ", x[::-1])

Our array:  [0 1 2 3 4 5 6 7 8 9]
First five elements:  [0 1 2 3 4]
Elements after index 5:  [5 6 7 8 9]
Middle sub-array:  [4 5 6]
Every other element:  [0 2 4 6 8]
Every other element, starting at index 1:  [1 3 5 7 9]
Elements in reversed order:  [9 8 7 6 5 4 3 2 1 0]


In [37]:
print("2-d array:\n", x2)
print("Two rows, three columns:\n", x2[:2, :3])

2-d array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
Two rows, three columns:
 [[3 5 2]
 [7 6 8]]


In [38]:
# Adding different dimension arrays into one

# Original array
print("Original 2-d array:\n", x2)

# Creating a 2x2 subarray from the original array
x2_sub = x2[:2, :2]
print("Sub-array:\n", x2_sub)

# Modifying sub-array
x2_sub[0, 0] = 88
print("Modified sub array:\n", x2_sub)

# Original array after sub-array changes
print("Original array after changes in sub-array:\n", x2)
print("Making a copy of the original array")

x2_sub_copy= x2[:2, :2].copy()
print("Copy of the original array:\n", x2_sub_copy)

# Modifying copied array
x2_sub_copy[0, 0] = 42
print("Copied array after changes:\n", x2_sub_copy)
print("Original array:\n", x2)

Original 2-d array:
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
Sub-array:
 [[3 5]
 [7 6]]
Modified sub array:
 [[88  5]
 [ 7  6]]
Original array after changes in sub-array:
 [[88  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
Making a copy of the original array
Copy of the original array:
 [[88  5]
 [ 7  6]]
Copied array after changes:
 [[42  5]
 [ 7  6]]
Original array:
 [[88  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [39]:
# Creating a sample array
x = np.array([1, 2, 3])

# Creating a 2-d array
grid = np.array([[9, 8, 7],
                [6, 5, 4]])

# Vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [40]:
# Horizontally stack the arrays
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### BAB VI (PANDAS DAN DATAFRAME)

##### Import Pandas

In [41]:
# Importing Pandas package using alias
import pandas as pd # type: ignore

##### Struktur Data Pandas

In [42]:
# Constructing pandas Series

# Creating an empty Series
x = pd.Series()
print("Empty series example: ", x)

Empty series example:  Series([], dtype: object)


In [43]:
# Another example of series

# Series example
series1 = pd.Series([10, 20, 30, 50])
series1

0    10
1    20
2    30
3    50
dtype: int64

In [44]:
# Re-indexing the default index column

series2 = pd.Series([10, 20, 30, 50], index=['a', 'b', 'c', 'd'])
series2

a    10
b    20
c    30
d    50
dtype: int64

In [45]:
# Data manipulation with Series

print("Adding 5 to a Series:\n", series2 + 5)
print("Filtering Series with greater than 30:\n", series2[series2 > 30])
print("Square root of Series elements:\n", np.sqrt(series2))

Adding 5 to a Series:
 a    15
b    25
c    35
d    55
dtype: int64
Filtering Series with greater than 30:
 d    50
dtype: int64
Square root of Series elements:
 a    3.162278
b    4.472136
c    5.477226
d    7.071068
dtype: float64


In [46]:
# Creating an empty DataFrame

df = pd.DataFrame()
print("DataFrame example:\n", df)

DataFrame example:
 Empty DataFrame
Columns: []
Index: []


In [47]:
# A sample list containing name and age
data = [['Tom', 10], ['Harry', 12], ['Jim', 13]]

# Creating a dataframe form given list with column names
df = pd.DataFrame(data, columns=['Name', 'Age'])
df

Name  Age
0    Tom   10
1  Harry   12
2    Jim   13

In [48]:
# Adding a column in existing dataframe
df['year'] = '2008'
df

Name  Age  year
0    Tom   10  2008
1  Harry   12  2008
2    Jim   13  2008

In [49]:
# Deleting a column in existing DataFrame

print("Original dataframe:\n", df)
del df['year']

print("Dataframe after del:\n", df)
df.pop('Age')

print("Dataframe after pop:\n", df)


Original dataframe:
     Name  Age  year
0    Tom   10  2008
1  Harry   12  2008
2    Jim   13  2008
Dataframe after del:
     Name  Age
0    Tom   10
1  Harry   12
2    Jim   13
Dataframe after pop:
     Name
0    Tom
1  Harry
2    Jim


In [50]:
# A sample dataframe containing compaany stack data

data = pd.DataFrame({'price': [95, 25, 85, 41],
                     'ticker': ['AXP', 'CSCO', 'DIS', 'MSFT'],
                     'company': ['American Express', 'Cisco', 'Walt Disney', 'Microsoft']})

data

price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft

##### Fungsi DataFrame

In [51]:
# Useful DataFrame functions

# Inspecting top 5 rows of a dataframe
print("Top five data:\n", data.head())

# Inspencting below 5 rows of a dataframe
print("Below 5 data:\n", data.tail())

Top five data:
    price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft
Below 5 data:
    price ticker           company
0     95    AXP  American Express
1     25   CSCO             Cisco
2     85    DIS       Walt Disney
3     41   MSFT         Microsoft


In [52]:
# Using describe() function to know statics

# Checking data type of the data
data.describe()

price
count   4.000000
mean   61.500000
std    33.798422
min    25.000000
25%    37.000000
50%    63.000000
75%    87.500000
max    95.000000

In [53]:
# Checking information of the DataFrame

# Information of the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   price    4 non-null      int64 
 1   ticker   4 non-null      object
 2   company  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


##### Menangani Data Hilang di DataFrame

In [54]:
# A sample DataFrame

# A sample DataFrame
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'], columns=['one', 'two', 'three'])

# Creating a data with missing values by reindexing
df2 = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df2

one       two     three
a  1.254414  1.419102 -0.743856
b       NaN       NaN       NaN
c -2.517437 -1.507096  1.149076
d       NaN       NaN       NaN
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
g       NaN       NaN       NaN
h -0.375666 -0.038224  0.367974

In [55]:
# Checking missing values using isnull()
print(df2.isnull())
missing_values_count = df2.isnull().sum()
print("Count of missing values:\n", missing_values_count)



     one    two  three
a  False  False  False
b   True   True   True
c  False  False  False
d   True   True   True
e  False  False  False
f  False  False  False
g   True   True   True
h  False  False  False
Count of missing values:
 one      3
two      3
three    3
dtype: int64


In [56]:
# Removing all rows containing missing value

df2 = df2.dropna()
df2

one       two     three
a  1.254414  1.419102 -0.743856
c -2.517437 -1.507096  1.149076
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
h -0.375666 -0.038224  0.367974

In [57]:
# Filling missing values

df3 = df2.fillna(0)
df3

one       two     three
a  1.254414  1.419102 -0.743856
c -2.517437 -1.507096  1.149076
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
h -0.375666 -0.038224  0.367974